import json
import argparse
import sys

# Fix for printing Russian characters in Windows consoles
sys.stdout.reconfigure(encoding='utf-8')

def is_original_article(nid) -> bool:
    """
    Checks if an article ID is an original (not a synthetic duplicate).
    Synthetic duplicates generated by generate_nlp_duplicates.py have IDs like '123_dup' or > 1000000.
    """
    if isinstance(nid, str) and nid.endswith('_dup'):
        return False
    try:
        if int(nid) >= 1000000:
            return False
    except ValueError:
        pass
    return True

def inspect_real_duplicates(full_data_path: str, clusters_path: str, limit: int = 5):
    try:
        with open(full_data_path, 'r', encoding='utf-8') as f:
            all_news = json.load(f)
    except Exception as e:
        print(f"Error loading {full_data_path}: {e}")
        return
        
    news_by_id = {item['id']: item for item in all_news}

    try:
        with open(clusters_path, 'r', encoding='utf-8') as f:
            clusters = json.load(f)
    except Exception as e:
        print(f"Error loading {clusters_path}: {e}")
        return

    real_dup_clusters = []
    for cluster in clusters:
        # Filter out synthetic duplicates robustly
        original_ids = [nid for nid in cluster.get('news_ids', []) if is_original_article(nid)]
        
        if len(original_ids) > 1:
            real_dup_clusters.append(original_ids)

    print(f'Найдено кластеров со скрытыми оригиналами (настоящие дубликаты): {len(real_dup_clusters)}')
    
    for i, cluster_ids in enumerate(real_dup_clusters[:limit]):
        print(f'\n=== Кластер {i+1} (Размер: {len(cluster_ids)}) ===')
        for nid in cluster_ids[:5]:
            news = news_by_id.get(nid, {})
            source = news.get("source", "?")
            title = news.get("title", "?")
            date = str(news.get("published_at", "?"))[:10]
            print(f'[{nid}] {source}: {title} ({date})')
            
        if len(cluster_ids) > 5:
            print(f"... и еще {len(cluster_ids) - 5} статей в кластере.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Inspect real (non-synthetic) duplicates in clusters")
    parser.add_argument("--full_data", type=str, default="data/news_dump_full.json", help="Path to full raw dataset")
    parser.add_argument("--clusters", type=str, default="data/clusters_output.json", help="Path to clusters output")
    parser.add_argument("--limit", type=int, default=5, help="Number of clusters to display")
    args = parser.parse_args()
    
    inspect_real_duplicates(args.full_data, args.clusters, args.limit)
